---
- name: Rust | Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
    - rustc
    - cargo

# - name: Rust | Cargo | Install [sshs]
#   ansible.builtin.command: "cargo install --git https://github.com/quantumsheep/sshs"
#   args:
#     creates: "{{ ansible_env.HOME }}/.cargo/bin/sshs"
