vars:
  vault_secret:
    sh: cat $HOME/.ansible-vault/vault.secret

tasks:
  docker-build:
    desc: Build dev Docker image
    env:
      vault_secret: "{{.vault_secret}}"
    cmds:
      - docker build -t devbox:latest .
