---
- name: "System | {{ distribution_name }} | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "System | {{ distribution_name }} | Install"
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
    state: present
  become: true
