version: '3'

tasks:
  default:
    desc: Show current tasks list.
    cmds:
      - task --list
  update:
    desc: Update system.
    platforms: [linux]
    cmds:
      - sudo apt-get update
  upgrade:
    desc: Upgrade system.
    platforms: [linux]
    deps: [update]
    cmds:
      - sudo apt-get upgrade -y
      - sudo apt-get autoremove -y
  dist-upgrade:
    desc: Dist-Upgrade system.
    platforms: [linux]
    deps: [upgrade]
    cmds:
      - sudo apt-get dist-upgrade -y
