# TODO: download obsidian .deb from github instead of flatpak
---
- name: Obsidian | Detect if Desktop Environment"
  ansible.builtin.set_fact:
    ansible_host_is_desktop_environment: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"

- name: "Obsidian | Install"
  community.general.flatpak:
    name: "md.obsidian.Obsidian"
    state: present
  when:
    - ansible_host_is_desktop_environment | bool
