---
# These steps are based on the official wezterm documentation: https://wezfurlong.org/wezterm/install/linux.html#__tabbed_1_3
- name: Add WezTerm GPG key
  become: true
  shell: "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg"

- name: Add WezTerm repository
  become: true
  shell: "echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list"

- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install WezTerm package
  become: true
  apt:
    name: wezterm
    state: present
