---
- name: "Install Google Cloud SDK"
  community.general.homebrew_cask:
    name: gcloud-cli
    state: present

- name: "Check installed components"
  ansible.builtin.command: gcloud components list --only-local-state --format="value(id)"
  register: gcloud_components
  changed_when: false
  failed_when: false

- name: "Install additional components"
  ansible.builtin.command: "gcloud components install {{ item }} --quiet"
  loop:
    - app-engine-go
    - pubsub-emulator
  when: item not in gcloud_components.stdout | default('')
