---
- name: "Neovim | Checking for Distribution Config: {{ distribution_name }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ distribution_name }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks: {{ distribution_name }}"
  ansible.builtin.include_tasks: "{{ distribution_name }}.yml"
  when: neovim_distribution_config.stat.exists

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
